-- MySQL Script generated by MySQL Workbench
-- mié 29 mar 2017 21:14:20 CEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema pictagram_bd
-- -----------------------------------------------------
-- Base de datos sobre la aplicación de proy_soft basada en el pictagram

-- -----------------------------------------------------
-- Schema pictagram_bd
--
-- Base de datos sobre la aplicación de proy_soft basada en el pictagram
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pictagram_bd` DEFAULT CHARACTER SET utf8 ;
USE `pictagram_bd` ;

-- -----------------------------------------------------
-- Table `pictagram_bd`.`Usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pictagram_bd`.`Usuarios` (
  `nickname` VARCHAR(10) NOT NULL,
  `email` VARCHAR(75) NOT NULL,
  `contra` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`nickname`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pictagram_bd`.`Fotos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pictagram_bd`.`Fotos` (
  `idFoto` INT NOT NULL AUTO_INCREMENT,
  `nickname` VARCHAR(10) NOT NULL,
  `titulo` VARCHAR(45) NOT NULL,
  `foto` LONGBLOB NOT NULL,
  `valoracion` INT NOT NULL,
  `descripcion` VARCHAR(300) NOT NULL,
  PRIMARY KEY (`idFoto`),
  INDEX `fk_Fotos_Usuarios1_idx` (`nickname` ASC),
  CONSTRAINT `fk_Fotos_Usuarios1`
    FOREIGN KEY (`nickname`)
    REFERENCES `pictagram_bd`.`Usuarios` (`nickname`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pictagram_bd`.`Comentario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pictagram_bd`.`Comentario` (
  `idComentario` INT NOT NULL AUTO_INCREMENT,
  `idFoto` INT NOT NULL,
  `texto` VARCHAR(300) NOT NULL,
  PRIMARY KEY (`idComentario`),
  INDEX `fk_Comentario_Fotos_idx` (`idFoto` ASC),
  CONSTRAINT `fk_Comentario_Fotos`
    FOREIGN KEY (`idFoto`)
    REFERENCES `pictagram_bd`.`Fotos` (`idFoto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pictagram_bd`.`Relacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pictagram_bd`.`Relacion` (
  `idRelacion` INT NOT NULL AUTO_INCREMENT,
  `nick_envia_pet` VARCHAR(10) NOT NULL,
  `nick_recibe_pet` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`idRelacion`),
  INDEX `fk_Relacion_Usuarios1_idx` (`nick_envia_pet` ASC),
  INDEX `fk_Relacion_Usuarios2_idx` (`nick_recibe_pet` ASC),
  CONSTRAINT `fk_Relacion_Usuarios1`
    FOREIGN KEY (`nick_envia_pet`)
    REFERENCES `pictagram_bd`.`Usuarios` (`nickname`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Relacion_Usuarios2`
    FOREIGN KEY (`nick_recibe_pet`)
    REFERENCES `pictagram_bd`.`Usuarios` (`nickname`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pictagram_bd`.`Mensaje`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pictagram_bd`.`Mensaje` (
  `idmensaje` INT NOT NULL AUTO_INCREMENT,
  `nick_envia_msj` VARCHAR(10) NOT NULL,
  `nick_recibe_msj` VARCHAR(10) NOT NULL,
  `mensaje` VARCHAR(300) NOT NULL,
  PRIMARY KEY (`idmensaje`),
  INDEX `fk_Mensaje_Usuarios1_idx` (`nick_envia_msj` ASC),
  INDEX `fk_Mensaje_Usuarios2_idx` (`nick_recibe_msj` ASC),
  CONSTRAINT `fk_Mensaje_Usuarios1`
    FOREIGN KEY (`nick_envia_msj`)
    REFERENCES `pictagram_bd`.`Usuarios` (`nickname`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Mensaje_Usuarios2`
    FOREIGN KEY (`nick_recibe_msj`)
    REFERENCES `pictagram_bd`.`Usuarios` (`nickname`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pictagram_bd`.`Amistades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pictagram_bd`.`Amistades` (
  `idAmistades` INT NOT NULL AUTO_INCREMENT,
  `nickname` VARCHAR(10) NOT NULL,
  `Amigo` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`idAmistades`),
  INDEX `fk_Amistades_Usuarios1_idx` (`nickname` ASC),
  INDEX `fk_Amistades_Usuarios2_idx` (`Amigo` ASC),
  CONSTRAINT `fk_Amistades_Usuarios1`
    FOREIGN KEY (`nickname`)
    REFERENCES `pictagram_bd`.`Usuarios` (`nickname`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Amistades_Usuarios2`
    FOREIGN KEY (`Amigo`)
    REFERENCES `pictagram_bd`.`Usuarios` (`nickname`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
